### ISSUE TITLE
[管理者介面]dashboard -> Last Orders ->點擊會員名稱 連結錯誤

### ISSUE THREAD

**Issue by byhuang** [byhuang/airmentor_web#14]

**Comment by horace12333** [comment]
巳修正，下班前會上傳到 https://demo.fun-so.com/airmentor

**Comment by horace12333** [comment]
巳修正，下班前會上傳到 https://demo.fun-so.com/airmentor

**Comment by byhuang** [comment]
還是遇到一樣的問題，請確認，謝謝
![image](https://cloud.githubusercontent.com/assets/10589736/7874710/1b9d0d26-05e6-11e5-9d39-5a31de3e6de7.png)
![image](https://cloud.githubusercontent.com/assets/10589736/7874715/3a35e5f0-05e6-11e5-8fd9-d335ca8e504c.png)

**Comment by horace12333** [comment]
ok 改上去了，我原本改好的是新會員註冊那邊的連結。

**Comment by byhuang** [comment]
已驗證 20150601
