### ISSUE TITLE
[訂單資訊] 建議多一個欄位，可以填寫給使用者的備註(由後臺管理者填寫)。

### ISSUE THREAD

**Issue by byhuang** [byhuang/airmentor_web#15]
目前的備註為後台管理者自己使用 
多一個備註留給使用者看
如: 貨單編號

**Comment by horace12333** [comment]
巳修正，下班前會上傳到 https://demo.fun-so.com/airmentor

**Comment by byhuang** [comment]
由於 #25 無法進行驗證

**Comment by horace12333** [comment]
後台訂單 > 修改 > 付款資訊 > 備註 
這個欄位有打字，會顯示在前台的會員訂單裡面

**Comment by byhuang** [comment]
已驗證 20150601
