### ISSUE TITLE
[購物車] 國家鎖定

### ISSUE THREAD

**Issue by byhuang** [byhuang/airmentor_web#16]
目前我們只打算支援台灣購買
     建議在商品品項設定不同國家

**Comment by horace12333** [comment]
改成如果在英文語系，不會出現「Add to cart」按紐。
巳修正，下班前會上傳到 https://demo.fun-so.com/airmentor

**Comment by byhuang** [comment]
能否使用使用者IP
或
寄件地址判斷...
避免不必要的糾紛

**Comment by ampgood** [comment]
這邊解決方法有兩種
1.你們去購買IP資料庫我們去對照IP資料庫的ip位置來鎖定;只是還是會有失準的時候。而且要定期更新
2.把購物地址改成鎖定台灣本島的下拉式選單;加註警示標語。

**Comment by horace12333** [comment]
ipligence 購買網址
http://www.ipligence.com/products

**Comment by byhuang** [comment]
能否使用 GOOGLE  
地址反查確認地理位置
http://blog.darkthread.net/post-2012-06-15-geocoding-api.aspx

判斷 
"types" : [ "country", "political" ]
"types" : [ "administrative_area_level_2", "political" ]

**Comment by byhuang** [comment]
一天可使用2500次~~我想能超過2500次的訂單~~我們可以直接跟GOOGLE購買次數了

**Comment by horace12333** [comment]
你的意思是當使用者到付款的最後一步打入地址的時候，我去查google api 確認他的輸入的地址是台灣才配送。

**Comment by byhuang** [comment]
是的
目前的需求是只配送台灣本島
較精確的做法是判斷配送地址
但是為了之後容易支援其他國家, 這樣似乎是比較彈性的做法

最好的做法是 從運送方式鎖定
配送方式加上屬性(支援國家)

使用者輸入地址->判斷國家->在跳出適合該國家的配送方式
若無合適的配送方式->跳出警示窗->"該國家無法配送 請透過其他代理商購買"

**Comment by byhuang** [comment]
請評估直接使用下拉式選單，只能選定台灣本島縣市再加上詳細地址的方式進行
  如附圖

![aaa](https://cloud.githubusercontent.com/assets/10589736/7950651/653e9c0e-09d0-11e5-9888-19525059b9db.png)

**Comment by horace12333** [comment]
地址判斷 是否為台灣巳完成，丟上 http://demo.fun-so.com/airmentor

**Comment by byhuang** [comment]
地址邏輯測試無誤，但下一步進行結帳時出現另外一個錯誤訊息

 Error Number: 1054

Unknown column 'invoice_type' in 'field list'

INSERT INTO `ai_order` (date_added, `options_shipping_method_id`, `shipping_fee`, `total`, `member_id`, `shipping_firstname`, `shipping_lastname`, `shipping_telephone`, `shipping_address`, `invoice_type`, `invoice_fax_id`, `invoice_prefix`, `options_payment_method_id`, `order_no`, `firstname`, `lastname`, `telephone`, `address`, `email`, `options_order_status_id`, `language_id`, `ip`, `user_agent`) VALUES (NOW(), 11, '150', 12110, '6', 'bryant 1111111111111111111111111', 'huang222222222222222222222222222', '0922117336', '新北市汐止區長興街二', '1', '20957874', '擎亞國際', '1', '11506030001', 'bryant 1111111111111111111111111', 'bryant 1111111111111111111111111', '0922117336', '新北市汐止區長興街', 'huang.bryant@gmail.com', 1, '1', '220.132.158.82', 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36')

Filename: core/MY_Model.php

Line Number: 22
應該為新增發票資訊延伸的問題~煩請協助處理

**Comment by ampgood** [comment]
發票欄位已新增.

**Comment by byhuang** [comment]
目前測試購物車資料已可寫入資料庫，但付款(歐付寶)頁面出現錯誤
![image](https://cloud.githubusercontent.com/assets/10589736/8026798/44af18e6-0db9-11e5-945d-4645ba5310d3.png)
請幫忙協助處理~~THANKS

**Comment by horace12333** [comment]
修正完畢，因為歐付寶有修改計算CheckMacValue 規則。
已丟上測試機 http://demo.fun-so.com/airmentor

**Comment by byhuang** [comment]
結帳完已進入資料庫~~
訂單編號 11506080041
1. 後台儀表板，Last order ->全部訂單狀態 
                           看不到此筆訂單 
                           必須切換到 已付款才能見到此訂單
2. 同個ISSUE, 在 購物車->訂單 
                          /chume/sales/order
                       ->全部訂單狀態
                           也看不到此筆訂單 
                           必須切換到 已付款才能見到此訂單

**Comment by byhuang** [comment]
已可以順地付款 2015/06/08
