### ISSUE TITLE
[商品結帳] 出現 Fatal error: Call to a member function insert() on a non-object in /home/funso/public_html/demo/airmentor/application/controllers/Payment.php on line 110

### ISSUE THREAD

**Issue by byhuang** [byhuang/airmentor_web#17]
![image](https://cloud.githubusercontent.com/assets/10589736/7804845/7f36bd2a-039b-11e5-924b-311189048193.png)

**Comment by horace12333** [comment]
巳修正，下班前會上傳到 https://demo.fun-so.com/airmentor

**Comment by byhuang** [comment]
已驗證，但出現另外一個錯誤。開新ISSUE #25 
https://github.com/byhuang/airmentor_web/issues/25
