### ISSUE TITLE
[商品管理]若商名品稱含有小括號，如"(台灣本島限定)"，加入購物車會發生錯誤

### ISSUE THREAD

**Issue by byhuang** [byhuang/airmentor_web#18]
![image](https://cloud.githubusercontent.com/assets/10589736/7804863/bfcf6a4e-039b-11e5-8489-dddc566bed92.png)

**Comment by horace12333** [comment]
巳修正，下班前會上傳到 https://demo.fun-so.com/airmentor

**Comment by byhuang** [comment]
已驗證 20150529
