### ISSUE TITLE
[products]規格內文修改 

### ISSUE THREAD

**Issue by byhuang** [byhuang/airmentor_web#19]
英文: APP available for iPhone 5, 5S, 6, 6+, iOS7, iOS8 -> APP available for iPhone 5, 5S, 6, 6+, iOS7
中文: iPhone 5, 5S, 6, 6+, 軟體版本 iOS7, iOS8 或以上 -> iPhone 5, 5S, 6, 6+, 軟體版本 iOS8 或以上

**Comment by crowmax** [comment]
已修改完成.

**Comment by byhuang** [comment]
英文: APP available for iPhone 5, 5S, 6, 6+, iOS7, iOS8 -> APP available for iPhone 5, 5S, 6, 6+, iOS8
Sorry..英文版打錯~~請幫忙再修正

**Comment by microds** [comment]
已修改.

**Comment by byhuang** [comment]
已驗證 20150602
