### ISSUE TITLE
[home]APP內文修改

### ISSUE THREAD

**Issue by byhuang** [byhuang/airmentor_web#20]
中:  手機需求：Android 4.4版本以上且支援藍芽4.0規格
       iPhone iOS 7.0以上之iPhone 5, 5S, 6, 6 plus 
       -> 
       手機需求：Android 4.4版本以上且支援藍芽4.0規格
       iPhone iOS 8.0以上之iPhone 5, 5S, 6, 6 plus

英: Android 4.4 or above on device with Bluetooth 4.0
      iOS 7 or above on iPhone 5, 5S, 6, 6 Plus
      ->
      Android 4.4 or above on device with Bluetooth 4.0
     iOS 8 or above on iPhone 5, 5S, 6, 6 Plus

**Comment by crowmax** [comment]
已修改完成.

**Comment by byhuang** [comment]
已驗證 20150529
