### ISSUE TITLE
[安全性] 能否在 登入/註冊/ 購物車結帳頁 直接導向 HTTPS 或 在後臺管理讓管理者設定某幾頁強迫使用HTTPS

### ISSUE THREAD

**Issue by byhuang** [byhuang/airmentor_web#21]
airmentor/member/login
airmentor/member/register
airmentor/cart

**Comment by horace12333** [comment]
如果你的主機有ssl，你可以直接設定主機導向。

**Comment by byhuang** [comment]
若不想每一頁都切HTTPS (如首頁之類的)
蠻多網站在一般網頁都是使用HTTP
在登入/ 註冊/購物/ 結帳時才使用HTTPS
應該是為了效能考量，雖然我們的網頁流量應該沒這麼大=.=
可以把此功能列為optional...
最後未實作~~~就全部都HTTPS吧

**Comment by horace12333** [comment]
因為用程式在特定頁面轉換成https的話，因為是進到畫面才會導頁，所以browser會導入一個警示頁面您將進入加密網站之類的，一般使用者的都會先覺得是不安全，通常他們不會去看序述...所以實務上沒人這樣做，如果有買ssl當然就整個站都要使用吧？

**Comment by byhuang** [comment]
用HEADER直接導向應該不會跑出警示頁面
若不用HEADER導向
也可以在連結時 某些頁面直接使用SSL(PCHOME似乎是這樣)

目前流量不大
先不考慮部分HTTP部分HTTPS
先全站HTTPS吧~~之後再說
