### ISSUE TITLE
[語言]自動判斷瀏覽器語系切換語言

### ISSUE THREAD

**Issue by byhuang** [byhuang/airmentor_web#24]
預設:英文
zh-tw:繁中

**Comment by horace12333** [comment]
修改成：只有在他第一次進到網站沒有手動選擇語系才會自動切換 。
下班前會放上去

**Comment by byhuang** [comment]
目前使用IE/Chrome/FireFox 系統為中文，但第一次進入還是英文版

**Comment by kong0422** [comment]
麻煩你關掉瀏覽器，讓session清掉，這樣就會是英文了，或是你直接開個無痕
如果你手動點了左上角的繁體中文，那會寫入session 變成當前的語系設定

**Comment by byhuang** [comment]
若使用者瀏覽器是中文
第一次進入網頁
看到的會是中文 還是 英文

我開了chrome(中文)的無痕視窗
開啟http://demo.fun-so.com/airmentor
進入的網頁是英文，但預期能看到中文網頁

**Comment by horace12333** [comment]
英文，如果你都沒有手動點過語系，就是英文
你知道什麼是無痕視窗嗎？知道的話你用那個打開網站就是英文。
判斷使用者瀏覽器的語系，是在客戶端才能做判斷，所以使用者都沒來過我們網站打開預設就是英文，但如果他手動點了左上角的繁體中文，session 就會寫入繁體，直到session清掉。

**Comment by byhuang** [comment]
這是自動判斷嗎?你知道"自動判斷" 跟 "記住上一次設定"的差別嗎??
無痕當然甚麼都沒有 沒有才需要自動判斷啊
一個支援多語系的系統 還要使用者切換 好聰明的網站

你可以說 "不在規格內" 或 "我不會判斷"
我們看看要怎麼處理驗收
我們自行找會判斷的來做

**Comment by ampgood** [comment]
目前跨國性企業網站的多國語言設計方式主要分為三種 :
方式一  ---自動判斷使用者預設的語言直接進行重導或詢問
方式二  --- 先進入官方主頁或語言選擇頁，使用者選擇語言後再進行重導
方式三 ---可由使用者設定未來要顯示的語言
這邊我們採用方案三；進行。
若要修改請貴司自行更改。
若修改後系統出錯請貴司自行修復；若需我方修復需另案報價。

黃大哥;
有溝通不良或者口氣讓您感覺不舒服的地方，先跟您道歉。
我想我們一開始議定的東西叫做套版的購物網站，
我們這邊已經盡量依照需求進行客製化，以求順利結案。
如果您覺得我們這邊能力不夠或有些沒辦法配合的部分；請您理解。
相信您也知道越聰明的程式需要花工程師越多時間去寫/修正。
工程師的時間成本是我們公司的營運成本，
請您理解。
另外附上幾個多種語系的系統也是需要使用者自己切換的網站給您參考，
http://store.apple.com/
http://www.nvidia.com/
http://www.ibm.com/

最後，案子其實我們到現在都沒拿到遞過去的合約，
所以能順利驗收我會謝謝陳博士，算賺到的。
不能驗收；那也無可奈何，
未收到的尾款我們自己攤平便是。

Tyson.

**Comment by byhuang** [comment]
WAIVE
