### ISSUE TITLE
[購物車] 結帳出現，交易失敗

### ISSUE THREAD

**Issue by byhuang** [byhuang/airmentor_web#25]
![image](https://cloud.githubusercontent.com/assets/10589736/7874648/de136a32-05e4-11e5-9501-1a9997599f95.png)

**Comment by horace12333** [comment]
歐付寶要求要訂單資料要輸入 產品名稱跟 產品描述，然後用來計算ChcekMacValue，目前已知 "()"，會造成計算錯誤，剛剛看後台的產品名稱 「氣質寶 - 全方位空氣品質偵測器 (限台灣本島購買)」，有小括號所以無法計算，我改成送到歐付寶之前會把小括號拿掉，麻煩你再確認一下

**Comment by byhuang** [comment]
已驗證 20150601
