### ISSUE TITLE
[Layout]部分電腦使用IE11，LAYOUT會錯誤

### ISSUE THREAD

**Issue by byhuang** [byhuang/airmentor_web#29]
Windows 8/ IE11
無功能選單
Screen resolution : full hd
![s__4456450](https://cloud.githubusercontent.com/assets/10589736/7932870/cde50d34-094d-11e5-9fe2-a91efc6b8697.jpg)

**Comment by horace12333** [comment]
我們這裡測試四五台IE11都正常耶？應該是客戶端瀏覽器自己的設定。

**Comment by byhuang** [comment]
特殊案例，WAIVE
