### ISSUE TITLE
[置頂/ 置底] 社群區域若無功能，建議先隱藏無功能的圖示

### ISSUE THREAD

**Issue by byhuang** [byhuang/airmentor_web#3]
![image](https://cloud.githubusercontent.com/assets/10589736/7804502/9bad969a-0396-11e5-8cb7-eb9eb22e8809.png)
![image](https://cloud.githubusercontent.com/assets/10589736/7804504/9dd84118-0396-11e5-81d5-26ab16ac9269.png)

**Comment by horace12333** [comment]
巳修正，下班前會上傳到 https://demo.fun-so.com/airmentor

**Comment by byhuang** [comment]
已修正 20150529
