### ISSUE TITLE
[首頁] HOME->Download Air Mentor App 加上連結

### ISSUE THREAD

**Issue by byhuang** [byhuang/airmentor_web#4]
Android: https://play.google.com/store/apps/details?id=com.coasia.airmentor
iOS: https://itunes.apple.com/app/id967846961

![image](https://cloud.githubusercontent.com/assets/10589736/7804518/ba0ccb6a-0396-11e5-8510-b26f0895ff6f.png)

**Comment by crowmax** [comment]
已修改完成.

**Comment by byhuang** [comment]
已修正 20150529
