### ISSUE TITLE
[註冊頁面]  多國語言(目前中/英文 混雜)

### ISSUE THREAD

**Issue by byhuang** [byhuang/airmentor_web#6]
![image](https://cloud.githubusercontent.com/assets/10589736/7804534/073f5a88-0397-11e5-8d4c-d74acfd6fd47.png)

**Comment by horace12333** [comment]
巳修正，下班前會上傳到 https://demo.fun-so.com/airmentor

**Comment by byhuang** [comment]
英文版，尚有中文文字，請確認
![image](https://cloud.githubusercontent.com/assets/10589736/7874885/6a68167e-05e8-11e5-9c8e-e8deced44fcc.png)

**Comment by byhuang** [comment]
已驗證 20150601
